# Generated by Django 3.2.6 on 2021-08-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
